### ISSUE TITLE
use CLI library for parsing command line argument for Java Client

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/url-frontier#6]
Will need to display help, description of the options and so on.

[picocli](https://picocli.info/) could be a good candidate

**Comment by jnioche** [comment]
http://jopt-simple.github.io/jopt-simple/

**Comment by kkrugler** [comment]
I've switched from args4j to picocli recently, and it's worked well for me.

**Comment by aecio** [comment]
I'm planning on switching projects to picocli as well. It claims to work
well with GraalVM, which is nice in case you decide to use GraalVM for
compiling native binaries.

**Comment by jnioche** [comment]
Picocli is pretty awesome indeed. Have committer an initial version of the client using it. Might need refining later.
thanks @aecio and @kkrugler
